### ISSUE TITLE
Please update the version of the API to 29.0

### ISSUE THREAD

**Issue by atorman** [forcedotcom/user-access-visualization#1]
From SalesforceHacker Blog Posting about User-Access-Visualization:

"Bob BuzzardOctober 9, 2013 at 1:09 AM
Running this in a developer edition with a packaging namespace threw a null pointer exception when retrieving the custom object information - changing the apiVersion of the UserAccessDetailsController.cls-meta.xml file to 29 (the repository has it at 25) fixed the problem for me."

**Comment by sfdcdoug-zz** [comment]
Pulled in a change that updates to 28.0
