### ISSUE TITLE
Namespace or Prefix Items?

### ISSUE THREAD

**Issue by hemmeter** [forcedotcom/user-access-visualization#2]
Many of the items in the repo use generic names (jQuery, js and css for static resources, for example). Since the code is not namespaced in a Managed Package, would it be best practice to prefix the names of pages, classes, components and resources so as not to cause issues when saving these items into an org with a decent amount of development? For example, our org has resources with all of those names already

Packaging this into a managed package would resolve this because it'd all be namespaced, but if that is not the plan, would it make sense to isolate all of these configuration objects via a name prefix?

**Comment by sfdcdoug-zz** [comment]
That's great feedback.  When I put this together, my primary goal was demo-ware.  As such, I wasn't thinking about those scenarios.  If you want to pull the repo and make those changes, I'd be happy to handle a pull request.

I do have a few other things I've thought about incorporating into this code base.  If / when I get an opportunity to do so, I'll look at incorporating your input (if you haven't given me a pull request).

Thanks!
--Doug

**Comment by hemmeter** [comment]
Sounds good. I figured I'd ask first to see if you had an opinion. I may do just that. This is a nice project you put together.

**Comment by hemmeter** [comment]
I submitted a pull request at #4
