### ISSUE TITLE
Applying this concept to summarize what's contained in a single Permission Set

### ISSUE THREAD

**Issue by hemmeter** [forcedotcom/user-access-visualization#6]
There are lots of detailed settings that could be in a Perm Set, but the default UI is really hard to navigate to see the big picture. What do you think about utilizing this visual to help someone see, at a glance, what is already setup in a Permission Set?

Seems like this kind of thing should be built into Salesforce in general, but maybe we can give them a start.

**Comment by sfdcdoug-zz** [comment]
Hi, Scott.  There are so many different ways one might visualize a permission set and it really depends on what you want to see.  We spent countless hours discussing ways to display a meaningful summary of a permission set on the main console page, but we could never come up with a good definition of "meaningful."  It's too easy to come up with wildly divergent use cases.  Furthermore, once you started factoring in the direction we wanted (and still want) to go with distributed administration, it became clear that such a summarization was something that we should table and perhaps revisit later.

This was one of many things that made it important for us to make sure to have good API support.  We knew that customers would want to be able to generate alternate visualizations / summaries of their permission sets.

You are welcome to use this as a starting point for your own definition of meaningful.  Feel free to completely fork the repo or generate a pull request if you feel you have something others would appreciate!

**Comment by hemmeter** [comment]
Maybe I will work on something. 

Providing a view that more closely resembles the old Profile page would make sense. For FLS, maybe just an indicator that more detail is behind it rather than going into so much detail. The Permission Set page and the new Profile page in Salesforce are really hard to navigate.
